const tech = {
  html5: 'HTML5 - markup language',
  css: 'CSS - style sheet language',
  tailwind: 'Tailwind CSS - CSS framework',
  javascript: 'JavaScript - programming language',
  python: 'Python - high-level programming language',
  django: 'Django - high-level Python web framework',
  bootstrap: 'Bootstrap - CSS framework',
  typescript: 'TypeScript - strongly typed programming language',
  jquery: 'jQuery - JavaScript library',
  reactjs: 'ReactJS - user interface library',
  nextjs: 'NextJS - React framework for production',
  swr: 'SWR - React hooks for data fetching',
  vercel: 'Vercel - platform for deploying and hosting',
  nodejs: 'NodeJS - back-end JavaScript runtime environment',
  express: 'ExpressJS - back end web application framework for Node.js',
  postgresql: 'PostgreSQL - relational database management system',
  prisma: 'Prisma - database toolkit for PostgreSQL',
  knexjs: 'KnexJS - SQL query builder for JavaScript',
  jwt: 'JSON Web Tokens - method for representing claims securely between two parties',
  restfulapis:
    'RESTful APIs - application programming interface that conforms to the constraints of REST',
  wordpress: 'WordPress - content management system',
  solidity: 'Solidity - implement smart contracts',
  hardhat: 'Hardhat - deploy to the Ethereum Rinkeby testnet',
  openzeppelin: 'OpenZeppelin - implement the NFT standard',
}

export const projects = [
  {
    name: 'OmitPlastic',
    slug: 'omitplastic',
    url: 'https://omitplastic.com/',
    imgsrc: '/images/project_omitplastic.jpg',
    github: 'https://github.com/gavinmgrant/omitplastic',
    description:
      'This full-stack app is designed to help people reduce plastic consumption by purchasing products with less plastic content.',
    bullets: [
      'Connected Prisma to a PostgreSQL database of product data hosted in the cloud by Heroku.',
      'Created a database schema with a model definition of the product objects using Prisma Client, a query builder.',
      'Utilized Tailwind CSS, a utility-first CSS framework, to efficiently style the UI of the app.',
      'Animated content with react-spring, which is a physics based animation library.',
      'Leveraged Next.js as the React library and for API routes for server-side API routes as the backend.',
      'Deployed the app to Vercel from a GitHub repo.',
    ],
    technologies: [
      tech.typescript,
      tech.reactjs,
      tech.nextjs,
      tech.tailwind,
      tech.postgresql,
      tech.prisma,
      tech.swr,
      tech.vercel,
    ],
  },
  {
    name: 'Anti-Inflammatory Foods',
    slug: 'anti-inflammatory-foods',
    url: 'https://gavinmgrant.pythonanywhere.com/',
    imgsrc: '/images/project_anti-inflammatory-foods.jpg',
    github: 'https://github.com/gavinmgrant/anti_inflammation',
    description:
      'This is a full-stack web app that allows users to browser foods with anti-inflammatory properties and add them to their own shopping list.',
    bullets: [
      'Utilizes Django on the back-end and JavaScript on the front-end.',
      "Completed as a the capstone project for HarvardX CS50's Web Programming with Python and JavaScript course.",
      'Leverages Bootstrap, an open-source front-end toolkit, to style the Django templates and HTML elements for a mobile-responsive design.',
      'Data in the list persists via the database, while localStorage is used to have the crossed out state persist on the front-end even across browser sessions.',
      'Hosted and deployed on the cloud via PythonAnywhere.',
    ],
    technologies: [
      tech.python,
      tech.django,
      tech.javascript,
      tech.bootstrap,
    ],
  },
  {
    name: 'SoundlyInvest',
    slug: 'soundlyinvest',
    url: 'https://soundlyinvest.com/',
    imgsrc: '/images/project_soundlyinvest.jpg',
    github: 'https://github.com/gavinmgrant/soundlyinvest-client',
    description:
      'This full-stack web application is a rental property calculator that allows users to save, update, and delete property investment reports.',
    bullets: [
      'Implemented a responsive client using JavaScript and React.js library that passes data to components via context and state.',
      'Architected RESTful API endpoints using Node.js/Express routers to perform CRUD operations POST, GET, PATCH, AND DELETE.',
      'Engineered a PostgreSQL database to save reports and user data while seamlessly integrating with the Express application.',
      'Integrated Google Maps Places API with the client to autocomplete property address inputs.',
    ],
    technologies: [
      tech.html5,
      tech.css,
      tech.javascript,
      tech.reactjs,
      tech.nodejs,
      tech.express,
      tech.postgresql,
      tech.knexjs,
      tech.jwt,
      tech.restfulapis,
    ],
  },
  {
    name: 'Permitful',
    slug: 'permitful',
    url: 'https://permitful.com/',
    imgsrc: '/images/project_permitful.jpg',
    github: 'https://github.com/gavinmgrant/permitful-client',
    description:
      'This full-stack web application allows users to visualize where all of the most recently updated building permits in a specific jurisdiction are located and save their favorites.',
    bullets: [
      'Implemented a responsive client using JavaScript and React.js library that passes data to components via context and state.',
      'Architected RESTful API endpoints using Node.js/Express routers to perform CRUD operations POST, GET, PATCH, AND DELETE.',
      'Engineered a PostgreSQL database to save reports and user data while seamlessly integrating with the Express application.',
      'Integrated Google Maps Places API with the client to autocomplete property address inputs.',
    ],
    technologies: [
      tech.html5,
      tech.css,
      tech.javascript,
      tech.reactjs,
      tech.nodejs,
      tech.express,
      tech.postgresql,
      tech.knexjs,
      tech.jwt,
      tech.restfulapis,
    ],
  },
  {
    name: 'ArchitectNFT',
    slug: 'architectnft',
    url: 'https://architectnft-client.vercel.app/',
    imgsrc: '/images/project_architectnft.jpg',
    github: 'https://github.com/gavinmgrant/architectnft',
    description:
      'This is a Web3 App that lets users connect their Ethereum wallet and mint an NFT to their wallet. The NFT is a random three word statement using the last name of famous architects.',
    bullets: [
      'Utilized Hardhat to quickly compile smart contracts and test them locally.',
      'Implemented the NFT standard using OpenZeppelin.',
      'Wrote smart contracts using Solidity.',
      'Used MetaMask to connect wallet to the Ethereum network.',
      'Deployed the app to Vercel from a GitHub repo.',
      'Project was a developed as part of a buildspace project.',
    ],
    technologies: [
      tech.solidity,
      tech.hardhat,
      tech.openzeppelin,
      tech.javascript,
      tech.reactjs,
      tech.nextjs,
      tech.vercel,
    ],
  },
  {
    name: 'Cadre General Contractors',
    slug: 'cadre',
    url: 'https://cadregeneralcontractors.com/',
    imgsrc: '/images/project_cadre.jpg',
    github: null,
    description:
      'This is website was designed for Seattle-based general contractor Cadre General Contractors to showcase their work and services.',
    bullets: [
      'Integrated the website into the WordPress content management system.',
      'Leveraged the Salient WordPress theme to create a responsive user experience.',
      'Designed with Search Engine Optimization best practices to increase visibility in search engines',
      "Created a dynamic portfolio page to showcase the client's projects and expertise.",
    ],
    technologies: [tech.wordpress],
  },
  {
    name: 'Name This City',
    slug: 'name-this-city',
    url: 'https://gavinmgrant.github.io/quiz-app/',
    imgsrc: '/images/project_name-this-city.jpg',
    github: 'https://github.com/gavinmgrant/quiz-app',
    description:
      'This is an urban geography quiz app that tests your knowledge of cities across the globe.',
    bullets: [
      'Developed single-purpose template generation and event handler functions in JavaScript.',
      'Utilized semantic HTML, along with CSS and the jQuery JavaScript library.',
      'Follows a11y best practices and allows full usability via the keyboard.',
      'Implemented a render() function, that conditionally regenerates the view each time the store is updated.',
    ],
    technologies: [tech.html5, tech.css, tech.javascript, tech.jquery],
  },
  {
    name: 'Happy Hour Helper',
    slug: 'happy-hour-helper',
    url: 'https://gavinmgrant.github.io/happy-hour-helper/',
    imgsrc: '/images/project_happy-hour-helper.jpg',
    github: 'https://github.com/gavinmgrant/happy-hour-helper',
    description:
      'This app recommends food and cocktail recipes for users planning a happy hour.',
    bullets: [
      'Built a responsive front-end application using JavaScript and the jQuery library.',
      'Utilized JS code separated into single-purpose, reusable, clearly named functions while returning an accessible DOM tree.',
      'Integrated the app with two external APIs that use search parameters and callbacks to retrieve pertinent data.',
      'Designed with accessibility in mind by using a11y best practices in semantic HTML.',
    ],
    technologies: [
      tech.html5,
      tech.css,
      tech.javascript,
      tech.jquery,
      tech.restfulapis,
    ],
  },
]
